### ISSUE TITLE
QRScanner.destroy() does not works

### ISSUE THREAD

**Issue by luxigo** [bitpay/cordova-plugin-qrscanner#151]
I still hear the camera auto-focus motor after using destroy() on android 6.0.1 / kernel 3.10.40-10100220

**Comment by andreagobetti** [comment]
On my Android 6 device it's working fine, have you tried logging the status this way?
```
QRScanner.destroy(function(status) {
    console.log(status);
});
```

**Comment by bitjson** [comment]
There was an issue with the destroy method on iOS which was fixed in 2.6.0. Since I can't reproduce any issue here, I'm going to close for now, please let me know if you're still having trouble. (And PRs welcome!)

**Comment by webquali** [comment]
version 3.4.0 still not works destroy and hide

**Comment by SimoneMSR** [comment]
This is still an issue with version 3.0.1. Camera just hangs on

**Comment by gerardoCD** [comment]
This is still an issue with version 3.0.1. Camera just hangs on. Plase Help Me :(

**Comment by DorelBesliu** [comment]
This is still an issue with version 3.0.1

**Comment by ewojjowe** [comment]
this might help [265#issuecomment-1054935914](https://github.com/bitpay/cordova-plugin-qrscanner/issues/265#issuecomment-1054935914)
